FROM python:3.12-slim as builder

WORKDIR /app

COPY requirements.txt ./

RUN apt-get update && apt-get install -y binutils

COPY . .

RUN pip install --no-cache-dir -r requirements.txt
RUN python -m PyInstaller --onefile lib/parallel.py
COPY ./sleep_data_large.csv /dist/sleep_data_large.csv

FROM scratch

WORKDIR /app

COPY --from=builder /dist .

ENTRYPOINT [ "./dist/parallel" ]
